name: Deploy TS Site

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install & Build
        env:
          NITRO_PRESET: static # اجبار Nitro به خروجی استاتیک برای GitHub Pages
        run: |
          npm install
          npm run build
          if [ -f .output/public/index.html ]; then
            cp .output/public/index.html .output/public/404.html
          fi

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './.output/public'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
