name: Deploy TS Site

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # آپدیت به نسخه ۲۲ برای رفع هشدار Deprecated

      - name: Install & Build
        run: |
          npm install
          npm run build

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # تغییر مسیر به پوشه خروجی Vite برای رفع ارور 404

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
